// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/akifkadioglu/kaydi/ent/list"
	"github.com/google/uuid"
)

// List is the model entity for the List schema.
type List struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Color holds the value of the "color" field.
	Color *string `json:"color,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ListQuery when eager-loading is set.
	Edges        ListEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ListEdges holds the relations/edges for other nodes in the graph.
type ListEdges struct {
	// Tasks holds the value of the tasks edge.
	Tasks []*Task `json:"tasks,omitempty"`
	// Users holds the value of the users edge.
	Users []*User `json:"users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TasksOrErr returns the Tasks value or an error if the edge
// was not loaded in eager-loading.
func (e ListEdges) TasksOrErr() ([]*Task, error) {
	if e.loadedTypes[0] {
		return e.Tasks, nil
	}
	return nil, &NotLoadedError{edge: "tasks"}
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e ListEdges) UsersOrErr() ([]*User, error) {
	if e.loadedTypes[1] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*List) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case list.FieldName, list.FieldColor:
			values[i] = new(sql.NullString)
		case list.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the List fields.
func (l *List) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case list.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				l.ID = *value
			}
		case list.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				l.Name = value.String
			}
		case list.FieldColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				l.Color = new(string)
				*l.Color = value.String
			}
		default:
			l.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the List.
// This includes values selected through modifiers, order, etc.
func (l *List) Value(name string) (ent.Value, error) {
	return l.selectValues.Get(name)
}

// QueryTasks queries the "tasks" edge of the List entity.
func (l *List) QueryTasks() *TaskQuery {
	return NewListClient(l.config).QueryTasks(l)
}

// QueryUsers queries the "users" edge of the List entity.
func (l *List) QueryUsers() *UserQuery {
	return NewListClient(l.config).QueryUsers(l)
}

// Update returns a builder for updating this List.
// Note that you need to call List.Unwrap() before calling this method if this List
// was returned from a transaction, and the transaction was committed or rolled back.
func (l *List) Update() *ListUpdateOne {
	return NewListClient(l.config).UpdateOne(l)
}

// Unwrap unwraps the List entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (l *List) Unwrap() *List {
	_tx, ok := l.config.driver.(*txDriver)
	if !ok {
		panic("ent: List is not a transactional entity")
	}
	l.config.driver = _tx.drv
	return l
}

// String implements the fmt.Stringer.
func (l *List) String() string {
	var builder strings.Builder
	builder.WriteString("List(")
	builder.WriteString(fmt.Sprintf("id=%v, ", l.ID))
	builder.WriteString("name=")
	builder.WriteString(l.Name)
	builder.WriteString(", ")
	if v := l.Color; v != nil {
		builder.WriteString("color=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// Lists is a parsable slice of List.
type Lists []*List
