// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/akifkadioglu/askida-kod/ent/schema"
	"github.com/akifkadioglu/askida-kod/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescActivationID is the schema descriptor for activation_id field.
	userDescActivationID := userFields[1].Descriptor()
	// user.DefaultActivationID holds the default value on creation for the activation_id field.
	user.DefaultActivationID = userDescActivationID.Default.(func() uuid.UUID)
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[5].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
